#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

bitcoind_hash_rate - Plugin to monitor the hash rate

=head1 CONFIGURATION

 [bitcoind*]
    user bitcoin

=head1 AUTHOR

Cedric Felizard

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/bitcoin-cli"}
DATA_DIR=${data_dir:-"/var/lib/bitcoin"}

if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Hash rate'
    echo 'graph_vlabel number of hashes per second'
    echo 'graph_category bitcoind'
    echo 'graph_info This graph shows the number of hashes per second.'
    echo 'bitcoind_hash_rate.label hash rate'
    echo 'bitcoind_hash_rate.info The current number of hashes per second.'
    exit 0
fi

echo "bitcoind_hash_rate.value $($BINARY -datadir=$DATA_DIR gethashespersec)"

