#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

bitcoind_connections - Plugin to monitor the number of open connections

=head1 CONFIGURATION

 [bitcoind*]
    user bitcoin
    env.binary bitcoin-cli

=head1 AUTHOR

Cedric Felizard

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"bitcoin-cli"}

if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Connection count'
    echo 'graph_vlabel number of connections'
    echo 'graph_category bitcoind'
    echo 'graph_info This graph shows the number of open connections.'
    echo 'bitcoind_connections.label connections'
    echo 'bitcoind_connections.info The current number of open connections.'
    exit 0
fi

echo "bitcoind_connections.value $($BINARY getconnectioncount)"

